/**@file filter_coefficients.h
 *	
 * @author Jenil Jain
 * @copyright Copyright 2015 Insensi Inc. All rights reserved.
 * This project is released under the GNU Public License.
 *
 * @brief File containing coefficients for various filters used by the program.
 *
 * All Coefficients are generated by program 
 * <a href="http://www-users.cs.york.ac.uk/~fisher/mkfilter/trad.html">mkfilter</a>.				
 * Corner frequencies can be calculated from 
 * <a href="http://www.sengpielaudio.com/calculator-cutoffFrequencies.htm">cut-off</a>. <BR>
 * 	
 * You can design your filter for a particular frequency just by changing the
 * parameters. All the filters used are IIR and the general equation for it, is
 *
 * y[n] = c0*x[n] + c1*x[n-1] + ... + cM*x[n-M] - ( d1*y[n-1] + d2*y[n-2] + ... + dN*y[n-N])
 * where N = no. of previous outputs &                  <BR>
 *      M = no. of previous inputs                      <BR>
 *      c1,c2,...,cM = input coefficients               <BR>
 *      d1,d2,...,dN = output coefficients              <BR>
 *      x[n] = input values                             <BR>
 *      y[n] = output values                            <BR>
 *
 * Example code for a 3rd order BandPass filter 
 * @code #define NZEROS 6
        #define NPOLES 6
        #define GAIN   6.035463052e+03

        static float xv[NZEROS+1], yv[NPOLES+1];
        static d_coef[NZEROS + 1] = {-0.7960564529, 4.8728234960, -12.5192737550, 
						        17.2778325650, -13.5086884650, 5.6733267812, 1.0}

        static c_coef[NZEROS + 1] = {-1, 0, 3, 0, -3, 0, 1}

        static int filterloop(int input)
        {
            xv[0] = xv[1]; xv[1] = xv[2]; xv[2] = xv[3]; 
            xv[3] = xv[4]; xv[4] = xv[5]; xv[5] = xv[6]; 
        yv[0] = yv[1]; yv[1] = yv[2]; yv[2] = yv[3]; 
        yv[3] = yv[4]; yv[4] = yv[5]; yv[5] = yv[6]; 

        xv[6] = input / GAIN;

        yv[6] = (c_coef[0] * xv[0]) + (c_coef[1] * xv[1]) + 
            (c_coef[2] * xv[2]) + (c_coef[3] * xv[3]) + 
            (c_coef[4] * xv[4]) + (c_coef[5] * xv[5]) +

            (d_coef[0] * yv[0]) + (d_coef[1] * yv[1]) + 
            (d_coef[2] * yv[2]) + (d_coef[3] * yv[3]) + 
            (d_coef[4] * yv[4]) + (d_coef[5] * yv[5]);
        return (int) yv[6];
        }
   @endcode	
 */

#ifndef FILTER_COEFFICIENTS_H
#define FILTER_COEFFICIENTS_H

#define BW              800	///< Bandwidth
#define NZEROS_POLES    6	/**< No. of zeros depends on order of the filter
                                For a 3rd order Bandpass filter, zeros and poles
                                are 6. But for a 3rd order Low-Pass or High-Pass
                                filter it is 3. So to keep the number of poles &
                                zeros constant we are using 3rd order Bandpass
                                and 6th order Low-pass for demodulation */

/// C coefficient for 3rd order Bandpass Filter
static const int c_coef_3rd_bp [NZEROS_POLES + 1] = {-1, 0, 3, 0, -3, 0, 1};

/// C coefficient for 6th order Lowpass Filter	
static const int c_coef_6th_lp [NZEROS_POLES + 1] = {1, 6, 15, 20, 15, 6, 1};	

/// Zeros for initializing xv and yv array
static const int zeros [NZEROS_POLES + 1] = {0, 0, 0, 0, 0, 0, 0};	



/************************************************************************************************/
/**************************************** 44100 Hz **********************************************/
/************************************************************************************************/


/*********************************  MARK BANDPASS  ********************************/

/**@brief Coefficients for Mark filters for 1200Hz and 44.1 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 44100
 * @param corner1 864.911
 * @param corner2 1664.911
 */
static const double gain_1200hz	                        = 6.035447139e+03 ;
static const double d_coef_1200hz [NZEROS_POLES + 1]    = {-0.7960564529,
4.8853503505, -12.5704962310, 17.3572300720, -13.5639614690, 5.6879115366, 1.0} ;


/**@brief Coefficients for Mark filters for 1300Hz and 44.1 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 44100
 * @param corner1 960.147
 * @param corner2 1760.147
 */
static const double gain_1300hz	                        = 6.035463052e+03 ;
static const double d_coef_1300hz [NZEROS_POLES + 1]    = {-0.7960564529, 
4.8728234960, -12.5192737550, 17.2778325650, -13.5086884650, 5.6733267812, 1.0} ;


/*********************************  SPACE BANDPASS  *******************************/

/**@brief Coefficients for Space filters for 2100Hz and 44.1 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 44100
 * @param corner1 1737.756
 * @param corner2 2537.756
 */
static const double gain_2100hz	                        = 6.035489699e+03 ;
static const double d_coef_2100hz [NZEROS_POLES + 1]    = {-0.7960564529, 
4.7372163175, -11.9731917700, 16.4353856510, -12.9194238570, 5.5154421711, 1.0} ;


/**@brief Coefficients for Space filters for 2200Hz and 44.1 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 44100
 * @param corner1 1737.756
 * @param corner2 2537.756
 */
static const double gain_2200hz	                        = 6.035490118e+03 ;
static const double d_coef_2200hz [NZEROS_POLES + 1]    = {-0.7960564529, 
4.7158930488, -11.8887264470, 16.3057248700, -12.8282792550, 5.4906159340, 1.0} ;


/**********************************  LOW PASS  ************************************/

/**@brief Coefficients for Low Pass filter for 1700Hz and 44.1 Khz sampling 
 *
 * Since 1700 is center of both ranges 1200-2200 and 1300-2100 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Low Pass
 * @param order 6
 * @param sample_rate 44100
 * @param corner1 1700
 */
static const double gain_lp_1700hz                      = 4.921530591e+05 ;
static const double d_coef_lp_1700hz [NZEROS_POLES + 1] = {-0.3911214670, 
2.7125767203, -7.8710687721, 12.2354456210, -10.7505803000, 5.0646181573, 1.0} ;



/************************************************************************************************/
/**************************************** 48000 Hz **********************************************/
/************************************************************************************************/


/*********************************  MARK BANDPASS  ********************************/

/**@brief Coefficients for Mark filters for 1200Hz and 48 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 48000
 * @param corner1 864.911
 * @param corner2 1664.911
 */
static const double gain_1200hz_48                      = 7.714531525e+03 ;
static const double d_coef_1200hz_48 [NZEROS_POLES + 1] = {-0.8109608719,
4.9734833008, -12.7760535460, 17.5948994070, -13.7006793120, 5.7192975419, 1.0} ;


/**@brief Coefficients for Mark filters for 1300Hz and 48 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 48000
 * @param corner1 960.147
 * @param corner2 1760.147
 */
static const double gain_1300hz_48                      = 7.714552008e+03 ;
static const double d_coef_1300hz_48 [NZEROS_POLES + 1] = {-0.8109608719, 
4.9627363056, -12.7321344850, 17.5269785470, -13.6535802120, 5.7069389474, 1.0} ;


/*********************************  SPACE BANDPASS  *******************************/

/**@brief Coefficients for Space filters for 2100Hz and 48 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 48000
 * @param corner1 1737.756
 * @param corner2 2537.756
 */
static const double gain_2100hz_48                      = 7.714586427e+03 ;
static const double d_coef_2100hz_48 [NZEROS_POLES + 1] = {-0.8109608719, 
4.8463050158, -12.2624122920, 16.8034849110, -13.1498469240, 5.5730478395, 1.0} ;


/**@brief Coefficients for Space filters for 2200Hz and 48 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 48000
 * @param corner1 1737.756
 * @param corner2 2537.756
 */
static const double gain_2200hz_48                      = 7.714586976e+03 ;
static const double d_coef_2200hz_48 [NZEROS_POLES + 1] = {-0.8109608719, 
4.8279816404, -12.1895052890, 16.6916642700, -13.0716609570, 5.5519767250, 1.0} ;


/**********************************  LOW PASS  ************************************/


/**@brief Coefficients for Low Pass filter for 1700Hz and 48 Khz sampling 
 *
 * Since 1700 is center of both ranges 1200-2200 and 1300-2100 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Low Pass
 * @param order 6
 * @param sample_rate 48000
 * @param corner1 1700
 */
static const double gain_lp_1700hz_48                   = 7.911546151e+05 ;
static const double d_coef_lp_1700hz_48 [NZEROS_POLES + 1] = {-0.4222972557, 
2.8967245878, -8.3083998149, 12.7576882370, -11.0643521500, 5.1405555009, 1.0} ;



/************************************************************************************************/
/**************************************** 16000 Hz **********************************************/
/************************************************************************************************/


/*********************************  MARK BANDPASS  ********************************/

static const double gain_1200hz_16                      = 3.450407729e+02 ;
static const double d_coef_1200hz_16 [NZEROS_POLES + 1] = {-0.5320753683,
	3.1381363581, -8.1321890445, 11.7763561920, -10.0414792500, 4.7835061525, 1.0} ;


static const double gain_1300hz_16                      = 7.714552008e+03 ;
static const double d_coef_1300hz_16 [NZEROS_POLES + 1] = {-0.8109608719, 
	4.9627363056, -12.7321344850, 17.5269785470, -13.6535802120, 5.7069389474, 1.0} ;


static const double gain_2100hz_16                      = 7.714586427e+03 ;
static const double d_coef_2100hz_16 [NZEROS_POLES + 1] = {-0.8109608719, 
	4.8463050158, -12.2624122920, 16.8034849110, -13.1498469240, 5.5730478395, 1.0} ;


static const double gain_2200hz_16                      = 3.450423755e+02;
static const double d_coef_2200hz_16 [NZEROS_POLES + 1] = {-0.5320753683, 
	2.2795472690, -5.2023382825, 7.1423622606, -6.4198613572, 3.4747465189, 1.0} ;


/**********************************  LOW PASS  ************************************/


static const double gain_lp_1700hz_16                   = 2.155293674e+03  ;
static const double d_coef_lp_1700hz_16 [NZEROS_POLES + 1] = {-0.0712022265, 
	0.6102683340, -2.2329558363, 4.4846591081, -5.2494746975, 3.4290109889, 1.0} ;



#endif
